const data = {
  products: [
    {
      "id": 1001,
      "category": "Category 4",
      "name": "Product 1",
      "image": "https://picsum.photos/400?image=524",
      "stock": false,
      "price": "2260.955",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1002,
      "category": "Category 2",
      "name": "Product 2",
      "image": "https://picsum.photos/400?image=48",
      "stock": false,
      "price": "2315.658",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-2",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1003,
      "category": "Category 4",
      "name": "Product 3",
      "image": "https://picsum.photos/400?image=376",
      "stock": false,
      "price": "3147.706",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-3",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1004,
      "category": "Category 2",
      "name": "Product 4",
      "image": "https://picsum.photos/400?image=739",
      "stock": false,
      "price": "3569.424",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-4",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1005,
      "category": "Category 1",
      "name": "Product 5",
      "image": "https://picsum.photos/400?image=216",
      "stock": false,
      "price": "3767.674",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-5",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1006,
      "category": "Category 3",
      "name": "Product 6",
      "image": "https://picsum.photos/400?image=808",
      "stock": true,
      "price": "2827.467",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-6",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1007,
      "category": "Category 3",
      "name": "Product 7",
      "image": "https://picsum.photos/400?image=760",
      "stock": true,
      "price": "2115.582",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-7",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1008,
      "category": "Category 1",
      "name": "Product 8",
      "image": "https://picsum.photos/400?image=156",
      "stock": false,
      "price": "3685.030",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-8",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1009,
      "category": "Category 4",
      "name": "Product 9",
      "image": "https://picsum.photos/400?image=581",
      "stock": false,
      "price": "3524.829",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-9",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1010,
      "category": "Category 3",
      "name": "Product 10",
      "image": "https://picsum.photos/400?image=884",
      "stock": false,
      "price": "3737.914",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-10",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1011,
      "category": "Category 2",
      "name": "Product 11",
      "image": "https://picsum.photos/400?image=276",
      "stock": true,
      "price": "3692.578",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-11",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1012,
      "category": "Category 1",
      "name": "Product 12",
      "image": "https://picsum.photos/400?image=656",
      "stock": false,
      "price": "2320.489",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-12",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1013,
      "category": "Category 2",
      "name": "Product 13",
      "image": "https://picsum.photos/400?image=962",
      "stock": false,
      "price": "3659.186",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-13",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1014,
      "category": "Category 4",
      "name": "Product 14",
      "image": "https://picsum.photos/400?image=575",
      "stock": false,
      "price": "3510.336",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-14",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1015,
      "category": "Category 4",
      "name": "Product 15",
      "image": "https://picsum.photos/400?image=820",
      "stock": true,
      "price": "3369.397",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-15",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1016,
      "category": "Category 3",
      "name": "Product 16",
      "image": "https://picsum.photos/400?image=370",
      "stock": true,
      "price": "2407.228",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-16",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1017,
      "category": "Category 3",
      "name": "Product 17",
      "image": "https://picsum.photos/400?image=311",
      "stock": true,
      "price": "2060.037",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-17",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1018,
      "category": "Category 3",
      "name": "Product 18",
      "image": "https://picsum.photos/400?image=930",
      "stock": true,
      "price": "2511.776",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-18",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1019,
      "category": "Category 4",
      "name": "Product 19",
      "image": "https://picsum.photos/400?image=578",
      "stock": true,
      "price": "1660.724",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-19",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1020,
      "category": "Category 3",
      "name": "Product 20",
      "image": "https://picsum.photos/400?image=970",
      "stock": true,
      "price": "1184.583",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-20",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1021,
      "category": "Category 3",
      "name": "Product 21",
      "image": "https://picsum.photos/400?image=635",
      "stock": false,
      "price": "3478.057",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-21",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1022,
      "category": "Category 2",
      "name": "Product 22",
      "image": "https://picsum.photos/400?image=522",
      "stock": false,
      "price": "2349.004",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-22",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1023,
      "category": "Category 1",
      "name": "Product 23",
      "image": "https://picsum.photos/400?image=276",
      "stock": true,
      "price": "1304.242",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-23",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1024,
      "category": "Category 4",
      "name": "Product 24",
      "image": "https://picsum.photos/400?image=66",
      "stock": true,
      "price": "2144.147",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-24",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1025,
      "category": "Category 4",
      "name": "Product 25",
      "image": "https://picsum.photos/400?image=6",
      "stock": false,
      "price": "1351.723",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-25",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1026,
      "category": "Category 2",
      "name": "Product 26",
      "image": "https://picsum.photos/400?image=158",
      "stock": false,
      "price": "1964.587",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-26",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1027,
      "category": "Category 1",
      "name": "Product 27",
      "image": "https://picsum.photos/400?image=100",
      "stock": true,
      "price": "3412.277",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-27",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1028,
      "category": "Category 2",
      "name": "Product 28",
      "image": "https://picsum.photos/400?image=184",
      "stock": true,
      "price": "1839.874",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-28",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1029,
      "category": "Category 1",
      "name": "Product 29",
      "image": "https://picsum.photos/400?image=397",
      "stock": true,
      "price": "2663.447",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-29",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1030,
      "category": "Category 1",
      "name": "Product 30",
      "image": "https://picsum.photos/400?image=420",
      "stock": false,
      "price": "3240.650",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-30",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1031,
      "category": "Category 2",
      "name": "Product 31",
      "image": "https://picsum.photos/400?image=207",
      "stock": true,
      "price": "1024.704",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-31",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1032,
      "category": "Category 2",
      "name": "Product 32",
      "image": "https://picsum.photos/400?image=729",
      "stock": false,
      "price": "2401.609",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-32",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1033,
      "category": "Category 4",
      "name": "Product 33",
      "image": "https://picsum.photos/400?image=84",
      "stock": false,
      "price": "1559.786",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-33",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1034,
      "category": "Category 1",
      "name": "Product 34",
      "image": "https://picsum.photos/400?image=48",
      "stock": true,
      "price": "2116.711",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-34",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1035,
      "category": "Category 4",
      "name": "Product 35",
      "image": "https://picsum.photos/400?image=999",
      "stock": false,
      "price": "1000.066",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-35",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1036,
      "category": "Category 2",
      "name": "Product 36",
      "image": "https://picsum.photos/400?image=812",
      "stock": false,
      "price": "3049.418",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-36",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1037,
      "category": "Category 2",
      "name": "Product 37",
      "image": "https://picsum.photos/400?image=927",
      "stock": true,
      "price": "1853.454",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-37",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1038,
      "category": "Category 3",
      "name": "Product 38",
      "image": "https://picsum.photos/400?image=305",
      "stock": false,
      "price": "2323.186",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-38",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1039,
      "category": "Category 4",
      "name": "Product 39",
      "image": "https://picsum.photos/400?image=274",
      "stock": false,
      "price": "2326.058",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-39",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1040,
      "category": "Category 2",
      "name": "Product 40",
      "image": "https://picsum.photos/400?image=229",
      "stock": false,
      "price": "1826.365",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-40",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1041,
      "category": "Category 1",
      "name": "Product 41",
      "image": "https://picsum.photos/400?image=739",
      "stock": true,
      "price": "1070.979",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-41",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1042,
      "category": "Category 3",
      "name": "Product 42",
      "image": "https://picsum.photos/400?image=91",
      "stock": true,
      "price": "2312.837",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-42",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1043,
      "category": "Category 4",
      "name": "Product 43",
      "image": "https://picsum.photos/400?image=411",
      "stock": true,
      "price": "1718.721",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-43",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1044,
      "category": "Category 4",
      "name": "Product 44",
      "image": "https://picsum.photos/400?image=111",
      "stock": false,
      "price": "1996.659",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-44",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1045,
      "category": "Category 1",
      "name": "Product 45",
      "image": "https://picsum.photos/400?image=22",
      "stock": true,
      "price": "3424.445",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-45",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1046,
      "category": "Category 1",
      "name": "Product 46",
      "image": "https://picsum.photos/400?image=88",
      "stock": false,
      "price": "2135.804",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-46",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1047,
      "category": "Category 4",
      "name": "Product 47",
      "image": "https://picsum.photos/400?image=249",
      "stock": true,
      "price": "3856.436",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-47",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1048,
      "category": "Category 1",
      "name": "Product 48",
      "image": "https://picsum.photos/400?image=579",
      "stock": true,
      "price": "3067.335",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-48",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1049,
      "category": "Category 1",
      "name": "Product 49",
      "image": "https://picsum.photos/400?image=488",
      "stock": true,
      "price": "3752.545",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-49",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1050,
      "category": "Category 4",
      "name": "Product 50",
      "image": "https://picsum.photos/400?image=842",
      "stock": false,
      "price": "3245.773",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-50",
      "brand": "armaani",
      "rating": 4
    },
  ]
}

export default data;