const guysData = {
  products: [
    {
      "id": 1001,
      "category": "Category 4",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_16",
      "image":'/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_16.webp',
      "stock": false,
      "price": "2260.955",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_16",
      "brand": "Hollister",
      "rating": 4
    },
    {
      "id": 1002,
      "category": "Category 2",
      "name": "skinny-chino-pants",
      "image": '/guys/blue-jeans/skinny-chino-pants.webp',
      "stock": false,
      "price": "2315.658",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "skinny-chino-pants",
      "brand": "Hollister",
      "rating": 4
    },
    {
      "id": 1003,
      "category": "Category 4",
      "name": "slim-straight-dark",
      "image": "/guys/blue-jeans/slim-straight-dark.webp",
      "stock": false,
      "price": "3147.706",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "slim-straight-dark",
      "brand": "Hollister",
      "rating": 3
    },
    {
      "id": 1004,
      "category": "Category 2",
      "name": "slim-straight-jeans-blue",
      "image": "/guys/blue-jeans/slim-straight-jeans-blue.webp",
      "stock": false,
      "price": "3569.424",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "slim-straight-jeans-blue",
      "brand": "Hollister",
      "rating": 3
    },
    {
      "id": 1005,
      "category": "Category 1",
      "name": "KIC_331-1391-2434-282_model1",
      "image": "/guys/boot/KIC_331-1391-2434-282_model1.webp",
      "stock": false,
      "price": "3767.674",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-1391-2434-282_model1",
      "brand": "Hollister",
      "rating": 4
    },
    {
      "id": 1006,
      "category": "Category 3",
      "name": "KIC_331-1528-2517-975_model1",
      "image": "/guys/taper/KIC_331-1528-2517-975_model1.webp",
      "stock": true,
      "price": "2827.467",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-1528-2517-975_model1",
      "brand": "Hollister",
      "rating": 4
    },
    {
      "id": 1007,
      "category": "Category 3",
      "name": "KIC_331-2951-2753-279_prod1",
      "image": "/guys/taper/KIC_331-2951-2753-279_prod1.webp",
      "stock": true,
      "price": "2115.582",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2951-2753-279_prod1",      
      "brand": "Hollister",
      "rating": 3
    },
    {
      "id": 1008,
      "category": "Category 1",
      "name": "KIC_331-2222-2693-280_prod2",
      "image": "/guys/vintage/KIC_331-2222-2693-280_prod2.webp",
      "stock": false,
      "price": "3685.030",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2222-2693-280_prod2",
      "brand": "Hollister",
      "rating": 4
    },
    {
      "id": 1009,
      "category": "Category 4",
      "name": "KIC_331-2222-2693-280_model3",
      "image": "/guys/vintage/KIC_331-2222-2693-280_model3.webp",
      "stock": false,
      "price": "3524.829",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2222-2693-280_model3",
      "brand": "Hollister",
      "rating": 3
    },
    {
      "id": 1010,
      "category": "Category 3",
      "name": "KIC_331-2203-2699-976_life1",
      "image": "/guys/vintage straight/KIC_331-2203-2699-976_life1.webp",
      "stock": false,
      "price": "3737.914",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2203-2699-976_life1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1011,
      "category": "Category 2",
      "name": "KIC_331-2890-2770-978_prod1",
      "image": "/guys/vintage straight/KIC_331-2890-2770-978_prod1.webp",
      "stock": true,
      "price": "3692.578",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2890-2770-978_prod1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1012,
      "category": "Category 1",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_21",
      "image": "/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_21.webp",
      "stock": false,
      "price": "2320.489",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_21",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1013,
      "category": "Category 2",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_18",
      "image": "/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_18.webp",
      "stock": false,
      "price": "3659.186",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_18",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1014,
      "category": "Category 4",
      "name": "KIC_331-2890-2770-978_prod1",
      "image": "/guys/vintage straight/KIC_331-2890-2770-978_prod1.webp",
      "stock": false,
      "price": "3510.336",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2890-2770-978_prod1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1015,
      "category": "Category 4",
      "name": "KIC_331-2222-2693-280_model3",
      "image": "/guys/vintage/KIC_331-2222-2693-280_model3.webp",
      "stock": true,
      "price": "3369.397",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2222-2693-280_model3",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1016,
      "category": "Category 3",
      "name": "KIC_331-2898-2739-281_prod1",
      "image": "/guys/taper/KIC_331-2898-2739-281_prod1.webp",
      "stock": true,
      "price": "2407.228",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2898-2739-281_prod1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1017,
      "category": "Category 3",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_17",
      "image": "/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_17.webp",
      "stock": true,
      "price": "2060.037",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_17",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1018,
      "category": "Category 3",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_19",
      "image": "/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_19.webp",
      "stock": true,
      "price": "2511.776",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_19",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1019,
      "category": "Category 4",
      "name": "KIC_331-2891-2771-278_prod1",
      "image": "/guys/vintage straight/KIC_331-2891-2771-278_prod1.webp",
      "stock": true,
      "price": "1660.724",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "KIC_331-2891-2771-278_prod1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1020,
      "category": "Category 3",
      "name": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_18",
      "image": "/guys/hco_2022_JanWk2_D_LP_Jeans_R_Fit_18.webp",
      "stock": true,
      "price": "1184.583",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "hco_2022_JanWk2_D_LP_Jeans_R_Fit_18",
      "brand": "armaani",
      "rating": 4
    },
  ]
}

export default guysData;